# -*- coding: utf-8 -*-
"""IntegrateAndFire(Students)FINAL-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-AYUWhJLzjke9S-ElynShqynRUsyEli

#  Below is Python code that runs an Integrate and Fire Model, Take some time to investigate the code and then complete the worksheet on Canvas titled "Worksheet 2, Integrate & Fire"
"""

# Commented out IPython magic to ensure Python compatibility.
# Jupyter: enable plot rendering inside the notebook (this allows us to actually show the output of the code visually)
# %matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

# --- Neuron Parameters (realistic, in mV and pA) ---
C = 200.0  #capacitance value
V_th = -55.0 #threshold value
V_reset = -65.0  #membrane potential value following hyperpolarization
V_rest =  -60.0 ##resting membrane potential value
I_ext = 300.0  #current
dt = 0.1   #time interval


T = 100          # total simulation time in ms
dt = 0.1         # time step in ms
time = np.arange(0, T, dt)  # time vector

# --- Initialize voltage and spike times ---
V = np.full_like(time, V_rest)  # set all values to resting voltage
spike_times = []

# --- Simulation Loop ---
for i in range(1, len(time)):
    dV = (I_ext / C) * dt       # ΔV = (I / C) * dt, in mV
    V[i] = V[i-1] + dV

    if V[i] >= V_th:
        V[i-1] = 40.0           # mark spike as +40 mV (for visualization)
        V[i] = V_reset
        spike_times.append(time[i])

# --- Plotting ---
plt.figure(figsize=(10, 4))
plt.plot(time, V, label='Neuronal Signal')
plt.axhline(V_th, color='r', linestyle='--', label='threshold')
plt.xlabel('Time (ms)') #what should the x be?
plt.ylabel('Membrane potential (Vm)') #what should the y be?
plt.title('I&F Model of a Traveling Action Potential') #what is a good title?
plt.legend() #can you think of a legend?
plt.grid(True)
plt.show()

## 8A - Creating a raster plot

plt.eventplot(spike_times, colors='black') #use the previously generated list with the spike times from the previous graph
plt.yticks([1], ['']) # Add ticks to y-axis
plt.xlabel('Time (s)') # Label for x
plt.ylabel('Action Potential Generated') # Label for y
plt.title('Raster Plot for a Traveling Action Potential') # Title
plt.show()

